// Generated by CoffeeScript 1.7.0
(function() {
  var fs, optimist, path, preresolve, resolve;

  fs = require('fs');

  path = require('path');

  resolve = require('resolve');

  preresolve = function(infile) {
    "Takes a file path to a JS file and transforms all the `require` statements\nin it into ones that have already been `require.resolve`d. This should make\nstarting up faster.";
    var basedir, input, output;
    basedir = path.resolve(path.dirname(infile));
    input = fs.readFileSync(infile, 'utf-8');
    output = input.replace(/(^[^"'].*\b)require\(([^\)]*)\)/g, function(_fullMatch, before, toRequireExpr) {
      var resolved, toRequire;
      console.log(require('util').inspect(arguments));
      console.log("toRequireExpr=" + toRequireExpr);
      toRequire = eval(toRequireExpr);
      if (resolve.isCore(toRequire)) {
        return "" + before + "require(" + (JSON.stringify(toRequire)) + ")";
      } else {
        resolved = resolve.sync(toRequire, {
          basedir: basedir
        });
        return "" + before + "require(" + (JSON.stringify("./" + (path.relative(basedir, resolved)))) + ")";
      }
    });
    return output;
  };

  if (require.main === module) {
    optimist = require('optimist');
    console.log(preresolve(optimist.argv._[0]));
  }

  module.exports = preresolve;

}).call(this);
