// Generated by CoffeeScript 1.7.1
(function() {
  var File, fs, infile, optimist, path, preresolve, resolve;

  fs = require('fs');

  path = require('path');

  resolve = require('resolve');

  File = require('vinyl');

  preresolve = function(file) {
    "Takes a vinyl-like JS file object and transforms all the `require` statements\nin it into ones that have already been `require.resolve`d. This should make\nstarting up faster.";
    var basedir, infile, input, output;
    basedir = path.resolve(path.dirname(infile));
    infile = file.path;
    input = file.contents.toString('utf-8');
    output = input.replace(/^([^"]*\b)require\(([^\)]*)\)/g, function(_fullMatch, before, toRequireExpr) {
      var resolved, toRequire;
      toRequire = eval(toRequireExpr);
      if (resolve.isCore(toRequire)) {
        return "" + before + "require(" + (JSON.stringify(toRequire)) + ")";
      } else {
        resolved = resolve.sync(toRequire, {
          basedir: basedir
        });
        return "" + before + "require(" + (JSON.stringify("./" + (path.relative(basedir, resolved)))) + ")";
      }
    });
    return new Buffer(output, 'utf-8');
  };

  if (require.main === module) {
    optimist = require('optimist');
    infile = optimist.argv._[0];
    console.log((preresolve(new File({
      cwd: process.cwd(),
      base: path.dirname(infile),
      path: infile,
      contents: fs.readFileSync(infile)
    }))).toString('utf-8'));
  }

  module.exports = preresolve;

}).call(this);
